import MobileDownload

extension EmployeeRecord {
    convenience init(_ record: EncodedRecord) {
        self.init()

        recNid = record.getRecNidOrZero(0)
        recKey = record.getString(1)
        recName = record.getString(2)

        var flags = EncodedFlags(flags: record.getString(3))

        overShortPassword = record.getString(4)
        truckAdjustPassword = record.getString(5)
        accessPassword = record.getString(6)
        orderPricePassword = record.getString(7)
        orderDiscPassword = record.getString(8)
        whseNid = record.getWhseNid(9)
        trkNid = record.getRecNidOrNil(10)
        distributorRecKey = record.getString(11)
        deliveriesUseTruckInventory = record.getInt(12) != 0
        depositPassword = record.getString(13)
        billingCodePricePassword = record.getString(14)
        forcePromoPassword = record.getString(15)
        posProductSetNid = record.getRecNidOrNil(16)
        uxSurveyNids = record.getString(17)
        WorkPhoneNumber = record.getString(18)
        InMarketPermission = eInMarketPermissionTypes(rawValue: record.getInt(19))!
        InMarketInventory = record.getString(20)
        IsKegRoute = record.getBool(21)
        IsRestrictedToAssignedWarehouse = record.getBool(22)
        Email = record.getString(23)
        PhoneNumber = record.getString(24)

        presellerFlag = flags.getFlag(0)
        driverFlag = flags.getFlag(1)
        commonCarrierFlag = flags.getFlag(2)
        isDistributorEmployee = flags.getFlag(3)
        mayChangePaymentTermsOnOrders = flags.getFlag(4)
        mayChangeProductDescriptionsOnOrders = flags.getFlag(5)
        requireHandheldServiceFlag = flags.getFlag(6)
        maySeeCosts = flags.getFlag(7)
        deliveryChargePlugin_OverrideCharges = flags.getFlag(8)
        mayVoidOrders = flags.getFlag(9)
        mayUpdateLiquorLicense = flags.getFlag(10)
        mayClearLineItemDeliveryAndFreightCharges = flags.getFlag(11)
        mayEditRetailPricesOnMobileDevices = flags.getFlag(12)
        whseManagerFlag = flags.getFlag(13)
        mayAddBarcodes = flags.getFlag(14)
        mayEnterProductWriteoffs = flags.getFlag(15)
        mayEnterInventory = flags.getFlag(16)
        mayProcessPurchasesWaitingForReceive = flags.getFlag(17)
        mayProcessProductXfersWaitingForVerification = flags.getFlag(18)
        mayProcessProductXfersWaitingForConfirmation = flags.getFlag(19)
        mayProcessOrdersWaitingForPicklist = flags.getFlag(20)
        mayApplyCredits = flags.getFlag(21)
        mayScheduleSpecialDeliveriesOnMobileDevices = flags.getFlag(22)
        qualifiedPromos_MayQualify = flags.getFlag(23)
        qualifiedPromos_MayDisqualify = flags.getFlag(24)
        mayChangePostedItemTransfers = flags.getFlag(25)
        ordersToLoads_MayEditTransferAfterProcessing = flags.getFlag(26)
        mayChangePostedPurchases = flags.getFlag(27)
        bSamplesPlugin_CanRequest = flags.getFlag(28)
        bPOSPlugin_DisallowPOSRequests = flags.getFlag(29)
        bPOSPlugin_DisallowPOSPlacements = flags.getFlag(30)
        bPOSPlugin_DisallowPOSPickups = flags.getFlag(31)
        bPOSPlugin_DisallowPOSRemovals = flags.getFlag(32)
        bPOSPlugin_DisallowPOSSurveys = flags.getFlag(33)
        bMaySetPromoDateOnOrders = flags.getFlag(34)
        mayPushOffDeliveries = flags.getFlag(35)
        bMayScoreUxSurveyResults = flags.getFlag(36)
        mayEnterProductRepacks = flags.getFlag(37)
        maySetTaxableOnMobileDevices = flags.getFlag(38)
        supervisorFlag = flags.getFlag(39)
        mayEnterOffInvoicePaymentsOnMobileDevices = flags.getFlag(40)
        requireDeliveryHandlingFlag = flags.getFlag(41)
        MayViewFuturePromotions = flags.getFlag(42)
        MayEditCustomerContactsOnMobileDevices = flags.getFlag(43)
        andrewsPlugin_CreateNewTradeReturn = flags.getFlag(44)
    }
}
